[build]
  command = "npm install && npm run prisma:generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"

# Use Netlify's Next.js Runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"